apiVersion: v1
kind: ConfigMap
metadata:
  name: daily-report-config
  namespace: daily-report
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "daily_report"

  # SMTP 邮件配置（非敏感）
  MAIL_HOST: "smtp.qq.com"
  MAIL_PORT: "587"
  MAIL_SECURE: "false"
  MAIL_FROM: "751397261@qq.com"
  MAIL_TO: "wangt@hcxtkj.com"
