apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daily-report-ingress
  namespace: daily-report
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: daily-report-service
            port:
              number: 80
