SET NAMES utf8mb4;
START TRANSACTION;
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-01', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-01-02', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-05', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-06', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-07', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-08', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-01-09', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-12', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-13', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-14', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-15', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-01-16', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-19', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-20', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-21', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-22', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-01-23', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-26', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-27', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-28', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-01-29', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-01-30', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-02', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-03', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-04', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-05', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-02-06', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-09', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-10', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-11', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-12', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-02-13', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-16', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-17', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-18', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-19', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-02-20', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-23', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-24', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-25', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-02-26', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-02-27', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-02', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-03', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-04', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-05', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-03-06', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-09', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-10', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-11', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-12', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-03-13', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-16', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-17', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-18', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-19', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-03-20', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-23', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-24', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-25', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-26', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-03-27', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-30', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-03-31', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-01', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-02', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-04-03', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-06', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-07', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-08', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-09', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-04-10', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-13', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-14', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-15', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-16', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-04-17', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-20', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-21', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-22', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-23', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-04-24', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-27', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-28', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-29', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-04-30', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-05-01', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-04', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-05', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-06', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-07', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-05-08', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-11', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-12', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-13', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-14', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-05-15', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-18', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-19', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-20', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-21', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-05-22', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-25', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-26', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-27', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-05-28', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-05-29', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-01', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-02', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-03', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-04', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-06-05', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-08', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-09', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-10', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-11', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-06-12', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-15', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-16', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-17', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-18', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-06-19', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-22', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-23', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-24', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-25', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-06-26', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-29', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-06-30', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-01', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-02', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-07-03', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-06', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-07', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-08', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-09', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-07-10', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-13', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-14', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-15', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-16', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-07-17', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-20', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-21', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-22', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-23', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-07-24', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-27', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-28', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-29', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-07-30', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-07-31', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-03', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-04', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-05', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-06', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-08-07', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-10', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-11', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-12', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-13', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-08-14', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-17', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-18', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-19', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-20', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-08-21', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-24', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-25', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-26', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-27', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-08-28', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-08-31', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-01', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-02', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-03', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-09-04', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-07', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-08', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-09', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-10', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-09-11', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-14', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-15', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-16', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-17', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-09-18', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-21', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-22', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-23', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-24', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-09-25', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-28', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-29', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-09-30', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-01', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-10-02', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-05', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-06', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-07', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-08', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-10-09', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-12', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-13', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-14', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-15', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-10-16', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-19', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-20', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-21', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-22', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-10-23', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-26', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-27', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-28', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-10-29', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-10-30', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-02', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-03', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-04', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-05', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-11-06', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-09', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-10', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-11', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-12', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-11-13', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-16', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-17', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-18', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-19', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-11-20', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-23', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-24', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-25', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-26', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-11-27', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-11-30', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-01', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-02', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-03', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-12-04', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-07', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-08', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-09', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-10', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-12-11', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-14', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-15', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-16', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-17', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-12-18', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-21', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-22', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-23', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-24', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id, other_reason) VALUES (2, '2026-12-25', 'other', 1, '请假');
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-28', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-29', 'existing_project', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-30', 'back_to_office', 1);
INSERT IGNORE INTO tomorrow_plans (engineer_id, report_date, destination, project_id) VALUES (2, '2026-12-31', 'back_to_office', 1);
COMMIT;